[build]
  command = "pnpm --filter @workspace/glowstore-dz... run build"
  publish = "artifacts/glowstore-dz/dist"

[[redirects]]
  from = "/api/*"
  to = "https://login-auth-api.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200